### ISSUE TITLE
Cannot build with gradlew build

### ISSUE THREAD

**Issue by Falsus2** [aria1th/SpawnProofHelper#3]
Simply states that I don't have the plugin with the ID of "fabric-loom" version 0.9-SNAPSHOT.

I have downloaded the plugin and it still states that I don't have it
Just trying to build the mod with the ability to place down light-weighted pressure plates

**Comment by aria1th** [comment]
seems many thing is broken, well not sure why would they change archived loom...

**Comment by aria1th** [comment]
Done
